POST http://localhost:7000/jwtDecode
#x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYm9yYXByYWUiLCJpYXQiOjE2NDU0MTU1NTgsImV4cCI6MTY0NTUwMTk1OH0.JkAIdnp_w9KkVsfAP7lU-Yi5LKHTJWZ9dE6zJZxkz7g
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYm9yYXByYWUiLCJpYXQiOjE2NDU0MTcxMjAsImV4cCI6MTY0NTUwMzUyMH0.m0qrE4Fu0YqO5UalSKQcP88IiRMgvDPcFHsLAMsAcRY